### ISSUE TITLE
Transaction type can't be a number when scheduling

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/CapitalBe#10]
When I try to schedule a transaction which is type "12" still it doesn't allow me . 
Screenshot for reference . 
![it s not atm](https://cloud.githubusercontent.com/assets/24365311/21351246/9d5c184e-c6e1-11e6-982c-c157a90eb347.png)

**Comment by humdingerb** [comment]
I don't know why it won't allow a type to be a number. That would be some intentional limitation.
The actual bug however, seems to be that when you edit the transaction, you actually can edit the type to be a number after all.

**Comment by dospuntos** [comment]
> I don't know why it won't allow a type to be a number. 

I asume it has to do with the use of cheques, and that numbered transactions are related to the cheque number.

> The actual bug however, seems to be that when you edit the transaction, you actually can edit the type to be a number after all.

After creating a scheduled transaction, it isn't related to the original transaction in any way. A new database record is created in the `scheduledlist` table with all required information. Deleting or changing the original transaction does not affect the scheduled transaction. You can even schedule the same transaction multiple times.

I think this makes sense, for example if you want to schedule a transaction starting in the future (just create a transaction, schedule it and delete the original).

Maybe it would make sense to check for scheduled transactions when making important changes to an account, like changing the currency or closing / deleting it?

**Comment by humdingerb** [comment]
With the transaction type feature removed, this "fixed" itself... :)
