### ISSUE TITLE
Dates in Reports

### ISSUE THREAD

**Issue by Pintaio** [HaikuArchives/CapitalBe#115]
If you have transactions throughout the year, when you go to Tools/Reports and select Subtotal by Quarter, Capital Be shows you the results up to a certain date: in my case from 01/01/2024 until 21/08/2024, despite the fact that I have transactions in December... Why not 31/12/2024?
Anyway, if you change starting or ending date directly in the box, CapitalBe refresh data automatically, but if you select the date in the calendar dropdown, it doesn't refresh the data.

Original report:
![screenshot 1](https://github.com/user-attachments/assets/286adf2a-09ed-4a59-8b97-6e951c902f63)

Report after changing the date in the dropdown:
![screenshot 2](https://github.com/user-attachments/assets/b50668ab-cb70-498b-8603-f9ce18179377)

**Comment by humdingerb** [comment]
I did fix the report getting updated after choosing a new date with the calendar button/window.

I do see a transaction I entered for december 2024 (though I dunno if making transactions into the future makes sense or should be allowed...), showing up in Q4 2024.
I see another issue though if I use a later start date, like April. Then the first tab isn't removed, but also says "Q2 2024". I'll have to look into the in more depth soon.

**Comment by humdingerb** [comment]
With 8a34ed96a566aa722f346110c820703dfffa01f9 I fixed the wrong column labelling I mentioned above.

@Pintaio, I'm not quite sure what you mean with:
> If you have transactions throughout the year, when you go to Tools/Reports and select Subtotal by Quarter, Capital Be shows you the results up to a certain date: in my case from 01/01/2024 until 21/08/2024, despite the fact that I have transactions in December... Why not 31/12/2024?

If I set an end date of 31.12.2024, I do get a Q4 column that shows the transaction I entered for 16.12.2024.
I need the exact steps to reproduce. Best in a new issue, as I think the main problem of this one is solved.
