### ISSUE TITLE
CapitalBe broken on 32bit Haiku

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/CapitalBe#119]
I was just about to build a new release, when I noticed that CapitalBe crashes when creating a transaction on Haiku 32bit.
It appears that went unnoticed for some time...

This is the debug report: 
[CapitalBe-1272-debug-14-10-2024-09-03-29.report.txt](https://github.com/user-attachments/files/17366032/CapitalBe-1272-debug-14-10-2024-09-03-29.report.txt)

It seems to crash somewhere down in the sqlite guts, after being called by [Database::AddTransaction()](https://github.com/HaikuArchives/CapitalBe/blob/master/src/Database.cpp#L685).

I've tracked down the breaking change to 8c9ab07f6b7283dd57f5791d200a83908e564f05

This is the diff of AddTransaction():

``` diff
@@ -626,30 +617,28 @@ Database::AddTransaction(const uint32& accountid, const uint32& id, const time_t
 
 	AddCategory(category, amount.IsNegative());
 
-	BString ecategory = EscapeIllegalCharacters(category);
-	BString epayee = EscapeIllegalCharacters(payee);
-	BString ememo = EscapeIllegalCharacters(memo);
+	CppSQLite3Buffer bufSQL;
+	bufSQL.format("INSERT INTO transactionlist VALUES(%li, %i, %Q, %i);", timestamp, id, category,
+		accountid);
+	DBCommand(bufSQL, "Database::AddTransaction:insert into transactionlist");
 
-	BString command = "INSERT INTO transactionlist VALUES(";
-	command << timestamp << ", " << id << ", '" << ecategory << "', " << accountid << ");";
-	DBCommand(command.String(), "Database::AddTransaction:insert into transactionlist");
-
-	command = "INSERT INTO account_";
-	command << accountid << " values(" << timestamp << ", " << id << ", " << date << ",'"
-			<< type.Type() << "', '" << epayee << "', " << amount.AsFixed() << ", '" << ecategory;
-	if (memo)
-		command << "', '" << ememo << "', '";
-	else
-		command << "', '', ";
+	BString _account, _status, command;
+	BString _memo = memo;
 
 	if (status == TRANS_CLEARED)
-		command << "cleared');";
+		_status << "cleared');";
 	else if (status == TRANS_RECONCILED)
-		command << "reconciled');";
+		_status << "reconciled');";
 	else
-		command << "open');";
+		_status << "open');";
 
-	DBCommand(command.String(), "Database::AddTransaction:insert into account");
+	_account << "account_" << accountid;
+
+	bufSQL.format("INSERT INTO %s VALUES(%i, %i, %li, %Q, %Q, %li, %Q, %Q, %Q)", _account.String(),
+		timestamp, id, date, type.Type(), payee, amount.AsFixed(), category, memo,
+		_status.String());
+
+	DBCommand(bufSQL, "Database::AddTransaction:insert into account");
 
 	Account* account = AccountByID(accountid);
 	if (account) {
```

@dospuntos , I don't know how much you remember of that change, maybe you can have a look...

I'll try working out what's going on with this change and where 64bit vs. 32bit differ that has the latter crash, but I'm famously bad at this sort of thing... :)

**Comment by korli** [comment]
@humdingerb according to https://www.sqlite.org/printf.html#the_optional_length_field for 64-bit fields %lld should be used, for instance for bigtime_t timestamp. But I'm worried seeing time_t (this one is 32-bit on x86, 64-bit on x86_64).

**Comment by korli** [comment]
B_PRIdTIME should work for time_t, B_PRIdBIGTIME for bigtime_t, ... should work.

**Comment by korli** [comment]
Please check with master.

**Comment by humdingerb** [comment]
Brilliant, that fixed it! Thanks very much, korli!

Now it's crashing when creating a new account in an empty ledger though... -> #120
