### ISSUE TITLE
32bit: Crash when add new account to empty/new ledger

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/CapitalBe#120]
If you create a new ledger, and create a new first account, CapitalBe (32bit only) crashes in [Database::SetCurrentAccount()](https://github.com/HaikuArchives/CapitalBe/blob/master/src/Database.cpp#L324):

[CapitalBe-1147-debug-15-10-2024-06-43-24.report.txt](https://github.com/user-attachments/files/17373941/CapitalBe-1147-debug-15-10-2024-06-43-24.report.txt)

Something to do with the `uint64` there? I'm so bad at this 32/64 bit stuff...

**Comment by korli** [comment]
The Notifier tries to call HandleNotiy() but can't, the values in obs are _komisch_:
```
obs: 0x18ff4578 {
      fFlags: 420556056
      fEnabled: true
     _vptr.Observer: 0x1
}
```
Needs more analysis. Could it be that an observer has registered itself, and not correct unregistered?

**Comment by korli** [comment]
Now creating the new ledger doesn't trigger a crash, but the list of accounts isn't cleared yet.

**Comment by humdingerb** [comment]
Thanks for looking into this. A bit over my head...
It seems to work quite well for on 64bit, haven't tested on 32bit.
I do see a crash sometimes when drag&dropping different ledgers on the window. BTW, if you haven't noticed yet, there is a folder "testdata" with a test file.

**Comment by korli** [comment]
Could it be that, before you add the multiple ledgers feature, that kind of issues wasn't possible? Running with the guarded heap on 64bit might help to uncover this kind of issue.

**Comment by humdingerb** [comment]
Get a reproducable crash on 64bit when dropping a ledger when using the guarded heap.
"Bohemian villages" to me, as the saying goes over here...

This is the debug trace (including the Terminal output at the top): 
[CapitalBe-1163-debug-16-10-2024-08-22-48.report.txt](https://github.com/user-attachments/files/17391928/CapitalBe-1163-debug-16-10-2024-08-22-48.report.txt)

The Terminal output:
```
$> LD_PRELOAD=libroot_debug.so MALLOC_DEBUG=grs25 ./CapitalBe
flags: used first dead
allocation size: 344
allocation base: 0x838ed4beea0
alignment: 16
allocating thread: 1163
freeing thread: 1189
alloc stack trace (12):
        <libroot.so> _Znwm + 0x20
        <_APP_> _ZN12RegisterViewC1EPKci + 0x54a
        <_APP_> _ZN10MainWindowC2E5BRect5BPath + 0x18ea
        <_APP_> _ZN3App15_ShowMainWindowE5BPath + 0x3b9
        <_APP_> _ZN3App10ReadyToRunEv + 0x1e6
        <libbe.so> _ZN12BApplication15DispatchMessageEP8BMessageP8BHandler + 0x467
        <libbe.so> _ZN7BLooper11task_looperEv + 0x294
        <libbe.so> _ZN12BApplication3RunEv + 0x21
        <_APP_> main + 0x45
        <_APP_> _start + 0x3e
        0x1b2cabcbe85 (lookup failed: Invalid Argument)
        0x7ffffe936258 (lookup failed: Invalid Argument)
free stack trace (13):
        <libroot.so> _Z5panicPKcz + 0x3dfa (nearest)
        <_APP_> _ZN15TransactionViewD0Ev + 0x29
        <libbe.so> _ZN5BViewD2Ev + 0x78
        <_APP_> _ZN12RegisterViewD1Ev + 0xf2
        <_APP_> _ZN12RegisterViewD0Ev + 0x18
        <libbe.so> _ZN5BViewD2Ev + 0x78
        <libbe.so> _ZN5BViewD0Ev + 0x11
        <libbe.so> _ZN7BWindowD1Ev + 0xbc
        <_APP_> _ZN10MainWindowD2Ev + 0x10c
        <_APP_> _ZN10MainWindowD0Ev + 0x18
        <libbe.so> _ZN7BLooper7_task0_EPv + 0x62
        <libroot.so> _thread_do_exit_work + 0x89 (nearest)
        0x7ffffe936258 (lookup failed: Invalid Argument)
Kill Thread
```

**Comment by korli** [comment]
Yeah, the TransactionView should also be removed in RegisterView::~RegisterView():
`gDatabase.RemoveObserver(fTransactionView);`

**Comment by humdingerb** [comment]
Did that.

```
diff --git a/src/RegisterView.cpp b/src/RegisterView.cpp
index 42d0ca4..7f8279d 100644
--- a/src/RegisterView.cpp
+++ b/src/RegisterView.cpp
@@ -122,6 +122,7 @@ RegisterView::~RegisterView()
                acc->RemoveObserver(this);
        }
        gDatabase.RemoveObserver(fCheckView);
+       gDatabase.RemoveObserver(fTransactionView);

```

Now this crash (guarded heap output at the top): 
[CapitalBe-1861-debug-17-10-2024-09-03-35.report.txt](https://github.com/user-attachments/files/17409315/CapitalBe-1861-debug-17-10-2024-09-03-35.report.txt)

> Could it be that, before you add the multiple ledgers feature, that kind of issues wasn't possible?

Forgot to answer that. Yes, definitely. Before there was no need for all the Observer cleanup, because there was no new ledger being loaded. Launched with one file until the app quits.
I was (mistakenly) assuming everything would reset "itself" when the MainWindow gets destroyed...

**Comment by korli** [comment]
OK, the RegisterView should also be removed in RegisterView::~RegisterView():
`gDatabase.RemoveObserver(this);`

**Comment by korli** [comment]
Cool. Theorically, the observers could keep a list of observables and automatically remove themselves on destruction, but this is more work.

**Comment by korli** [comment]
@humdingerb I see a new release, this can maybe be closed?

**Comment by humdingerb** [comment]
Indeed, forgot about this ticket... Thanks!
