### ISSUE TITLE
Add, delete account buttons on the main window

### ISSUE THREAD

**Issue by bach5000** [HaikuArchives/CapitalBe#22]
If we have a Help button, why shouldn't there be Add/Delete account buttons?
If there's space, a Settings button with a gear icon could be placed next to these buttons, too.

**Comment by mmuman** [comment]
I'm not sure, it's not a very common operation, and deleting an account surely would need proper validation to avoid loosing data. At least Grisbi doesn't have those.

**Comment by scottmc** [comment]
I agree with mmuman on this.  These aren't needed.  Closing issue.
