### ISSUE TITLE
Change icon style

### ISSUE THREAD

**Issue by BachToTheFuture** [HaikuArchives/CapitalBe#23]
Similar to #3, but instead of just the app's icon, some icons like the little blue "i" and the exclamation point on alert windows and the help button should be changed to Haiku style.

![info](https://user-images.githubusercontent.com/17076625/48168059-839e1980-e2b3-11e8-9bd2-f6a38b89d6cb.png)

![delete](https://user-images.githubusercontent.com/17076625/48168063-84cf4680-e2b3-11e8-873c-3390fe6129dd.png)

**Comment by CalebCDE** [comment]
Please close that issue, the user dospuntos was created a new one :-)

**Comment by humdingerb** [comment]
The app icon was changed, the rest of the icons in the app's GUI have not.

**Comment by CalebCDE** [comment]
> The app icon was changed, the rest of the icons in the app's GUI have not.

True...  sorry about that. Well, a real-one... the app icon was changed, good, but in the aboutwindows i still see the old-pixeled-one

![screenshot2](https://github.com/HaikuArchives/CapitalBe/assets/14283509/66c20b3f-80ea-487c-99ff-eb28d7935bf4)

**Comment by humdingerb** [comment]
You probably have an older CapitalBe binary around, and the AboutWindow mistakenly picks that one instead.
