### ISSUE TITLE
Help window with search option

### ISSUE THREAD

**Issue by BachToTheFuture** [HaikuArchives/CapitalBe#24]
It would be nice to have a little search box somewhere where you can search what you need help with and the help window will display the correct, relavant docs.

**Comment by mmuman** [comment]
Another option would be generating HTML docs and ask [BeHappy](https://github.com/mmuman/BeHappy) to display the proper info for the item. But BeHappy isn't in a really good shape at the moment.

**Comment by CalebCDE** [comment]
![screenshot3](https://github.com/HaikuArchives/CapitalBe/assets/14283509/c31066a6-0537-454a-b8a0-af6dd00e7783)

**Comment by humdingerb** [comment]
Fixed with the new HTML documentation.
