### ISSUE TITLE
[enhancement] Add localization support

### ISSUE THREAD

**Issue by unspacyar** [HaikuArchives/CapitalBe#33]
Would be nice to have the CapitalBe localizated, through the use of catkeys.  

I can contribute with the spanish translation.  May I help translating the "CapitalEnglish" file available in src/R5LanguageFiles/ ?

**Comment by humdingerb** [comment]
Sure. If nothing else, we'll see how localization aware CapitalBe's non-layoutmangemental code is... :)
Just to be sure, you'll need to replace the CAPITALIZED parts in the "CapitalEnglish" file with your translations.

**Comment by unspacyar** [comment]
Thanks for your answer, @humdingerb .  Are you sure that the strings to be translated are the CAPITALIZED ones?  The app shows the text in CamelCase...

**Comment by humdingerb** [comment]
I'm quite sure. The file src/R5LanguageFiles/CapitalEnglish has the strings that appear when you choose  "CapitalEnglish" from the Program|Language menu. Which has all strings in all-caps.
