### ISSUE TITLE
No DD/MM/YYYY format under date

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/CapitalBe#6]
In the dialog box for date something like DD/MM/YYYY format could be displayed which would help users in determining the format the app is using .

**Comment by scottmc** [comment]
Maybe consider using the standard ISO 8601 date format, which would be YYYY/MM/DD.

**Comment by humdingerb** [comment]
Perfect would be to use Haiku's locale kit to use the format set by the user in the Locale preferences panel.
