### ISSUE TITLE
User-settable negative amount colour?

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/CapitalBe#65]
As I've mentioned in #64, depending on your system colours, the red B_FAILURE_COLOR can be quite unreadable. See:

![color_new](https://github.com/HaikuArchives/CapitalBe/assets/6107158/c6e09ae3-283c-47f3-86df-d0b9039c6e28)

Should we let the user set a colour for those neg. numbers in the Settings dialog?
There could be a preview of a neg. number on an unselected and selected background and in case of a closed account.

Opinions? (@dospuntos ?)

**Comment by dospuntos** [comment]
@humdingerb - I'm not sure about this, but I think that since B_FAILURE_COLOR is configurable in the Haiku color settings, it might be a bit strange to have a setting for it in CapitalBe as well (unless all colors are customizable). After all, I think red is a common color for negative numbers in accounting. 

If the contrast is good enough with the default color scheme, maybe we can assume that if a user is able to configure the system colors, they are also able to change the B_FAILURE_COLOR to something that works with their current settings?

How about displaying the balance in bold text? It would stand out a bit more, which makes sense also for positive numbers.

**Comment by humdingerb** [comment]
>... it might be a bit strange to have a setting for it in CapitalBe as well 
> (unless all colors are customizable). After all, I think red is a common color
> for negative numbers in accounting.

Granted. Although, all the other colours in CapitalBe are just as used by their role in all of Haiku - list background/text, selected list background/text and tinted versions for closed accounts. In those traditional roles, they are sure to work together.

B_FAILURE_COLOR isn't used much in the anywhere, never as text on list items.

> If the contrast is good enough with the default color scheme, maybe we can assume 
> that if a user is able to configure the system colors, they are also able to change 
> the B_FAILURE_COLOR to something that works with their current settings?

Assigning B_FAILURE_COLOR to negative numbers is not quite right anyway. It's just "accidentally" also red as negative numbers, but the role of "failure" isn't really linked to neg. numbers. If anything, the colour should be hard-coded to red.
Also, how does the user know CapitalBe uses B_FAILURE_COLOR for neg. numbers and they can change it in Appearances?

> How about displaying the balance in bold text? It would stand out a bit more, which makes sense also for positive numbers.

Maybe. Or is it distracting? Some screenshots testing that:

![positves](https://github.com/HaikuArchives/CapitalBe/assets/6107158/fbaba098-646a-4b05-96cc-c6f44efe2486)

![negatives](https://github.com/HaikuArchives/CapitalBe/assets/6107158/da89047a-df6d-4aca-a5db-3093108a36a3)

At least for the issue of the red being unreadable on certain colours - imagine someone using red as selected list background... :) - bolding doesn't solve it.

**Comment by dospuntos** [comment]
Thanks for the screenshots, I take back my idea of showing the balance in bold, I agree that it is distracting more than anything.

> Assigning B_FAILURE_COLOR to negative numbers is not quite right anyway.

You're right, a setting for "Negative numbers" makes sense, with default to red.

**Comment by humdingerb** [comment]
Alright, I'll be working on that next. Any objections to merging #64 first?

**Comment by dospuntos** [comment]
Go ahead, LGTM 👍

**Comment by humdingerb** [comment]
Thanks!

**Comment by humdingerb** [comment]
Fixed with #66
