### ISSUE TITLE
Scheduled transactions require relaunch

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/CapitalBe#74]
Do this:
* Enter a new transaction with a date in the past
* Select it and do a "Transaction|Schedule this transaction"
* Make it a monthly repeat

After closing the window, no new entries appear in the transaction list.
Only after relaunching the app you'll see the added monthly transactions.

**Comment by dospuntos** [comment]
There's a function call in the MainWindow constructor (`HandleScheduledTransactions()`) that takes care of pending schedules, but as you see only on startup. There should probably be a looper that runs this at a certain interval. The function keeps track of what it has done, so there's no harm in running it often. Or at least run it when the scheduling window is closed.

@humdingerb - Do you know of any application that does something similar, so I can look at how it can be done? And what would be a reasonable frequency? Not sure if we're talking milliseconds or hours...

**Comment by humdingerb** [comment]
I see.
As you said, the function should be called when the a transfer or transaction edit window was closed.

Additionally, to frequently update, there's BMessageRunner(). Like:

	BMessage message(M_SCHEDULE_TRANSACTIONS);
	fRunner = new BMessageRunner(this, &message, kSeconds * 360000000);

Maybe every 30 seconds?
