### ISSUE TITLE
Memos of scheduled transactions have a "20" instead of a space

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/CapitalBe#75]
If you schedule a transaction, the added memos show a "20" instead of a space, e.g. "Monthy salary" becomes "Monthly20salary"

**Comment by dospuntos** [comment]
The Split window when editing a transaction has a similar problem, special characters are not escaped. I'm working on a PR for this.

![screenshot1](https://github.com/HaikuArchives/CapitalBe/assets/12958546/501e35ab-ab6b-4617-9a16-efac98f32e3e)
