### ISSUE TITLE
Can't change Decimal and Thousands Separators

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/CapitalBe#8]
In India 150,000 rupees becomes 1.5 lakh rupees, written as ₹1,50,000 or INR 1,50,000, while 30,000,000 (thirty million) rupees becomes 3 crore rupees, written as ₹3,00,00,000 with commas at the thousand, lakh, and crore levels, and 1,000,000,000 (one billion) rupees (one hundred crore rupees) is written ₹1,00,00,00,000.
Whereas your software uses only western system not Indian System . 
A option to toggle would be great .

**Comment by humdingerb** [comment]
Have you changed the formatting to Indian in the Locale preferences? Though it's more than likel that the software doesn't use the system settings. I think it pre-dates Haiku's localization...
